---
title: WGTWO
timezone: UTC
collections:
  news:
    title: News
    output: true
    permalink: "/news/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: post@wgtwo.com
description: Working Group TWo
baseurl: ''
url: ''
excerpt_separator: "<!--more-->"
plugins:
- jekyll-feed
