---
title: WGTWO
timezone: UTC
collections:
  media:
    title: media
    output: true
    permalink: "/media/:name"
  uploads:
    title: Uploads
    output: true
email: post@wgtwo.com
description: Working Group TWo
baseurl: ''
url: ''
excerpt_separator: "<!--more-->"
plugins:
- jekyll-feed
