name: PR Build Website

on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "blog/**"
      - "website/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'website skip')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Prettier & Build & Test for broken links
        run: |
          cd website 
          yarn && yarn prettier:check && yarn build && yarn links:test
