name: PR Previewer (Dev Site)

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
    paths:
      - "docs/**"
      - "blog/**"
      - "website/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'devpages')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Prettier & Build Website
        run: |
          cd website
          yarn install && yarn prettier
          if [ ! -n "$(git status --porcelain)" ]; then
            yarn buildDevpage
            exit 0
          fi
          git config --global user.name 'GitHub Action'
          git config --global user.email 'github-action@users.noreply.github.com'
          git commit -am "[Prettier] Fix formatting"
          git push
          exit 1

      - name: Deploy Website 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: dev-pages
          folder: website/build
