name: PR Previewer (Dev Site)

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
      - "dev-pages-actions"
    paths:
      - "docs/**"
      - "blog/**"
      - "website/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'devpages')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev-pages
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Rebase
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'github-action@users.noreply.github.com'
          git branch
          git branch -r
          git rebase origin/${{ github.head_ref }}
          git push --force
          exit 1
      - name: Prettier & Build
        run: |
          cd website
          yarn && yarn prettier:check && yarn build
